/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package prir.client;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import org.tc33.jheatchart.HeatChart;

/**
 *
 * @author reynev
 */
public class ChartPanel extends javax.swing.JPanel {

    HeatChart chart;
    Image mapImg = null;
            
    public ChartPanel() {
        initComponents();
    }
    
    void setChart(HeatChart c){
        chart = c;
        mapImg = chart.getChartImage();
        System.err.println("H:" + chart.getChartSize().height + " W: " + chart.getChartSize().width);
    }
    
    @Override
    public void paintComponent (Graphics g){
        if(mapImg != null)
            g.drawImage(mapImg, 0 , 0, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
