/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package prir.client;

import java.awt.Color;
import java.awt.Image;
import org.fsf.*;


/**
 *
 * @author reynev
 */
public class PlotFrame extends javax.swing.JFrame {
    HeatMap hMap;
    double [][] map;
    Image mapImg = null;
    /**
     * Creates new form PlotFrame
     */
    public PlotFrame(int n) {
        initComponents();
        map = new double[n][n];
        hMap = new HeatMap(map, true, Gradient.GRADIENT_HOT);
        jScrollPane1.setViewportView(hMap);
        hMap.setDrawLegend(true);
        hMap.setDrawXTicks(true);
        hMap.setDrawYTicks(true);
        hMap.setCoordinateBounds(0, n, 0, n);
        hMap.setDrawLegend(true);
        
        setBounds(50, 50, hMap.getWidth(), hMap.getHeight());
        int i;
        for(i = 0 ; i < n ; ++i){
            map[0][i] = 0;
            map[i][0] = 0;
            map[0][n-1] = 0;
        }
        for(i = 0 ; i < n ; ++i)
            map[n-1][i] = 100;
        hMap.updateData(map, true);
        hMap.repaint();
        pack();
    }
    
    void addValue(int i, int j, double value){
        map[i][j] = value;
        hMap.updateData(map, true);
        hMap.repaint();
        System.out.printf("Added to plot[%d %d] %f \n",i,j,value);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlotFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PlotFrame pf = new PlotFrame(10);
                pf.setVisible(true);
                pf.addValue(1, 1, 0);
                pf.addValue(1, 2, 10);
                pf.addValue(1, 3, 20);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
